
GET http://localhost:8080/tarefa

###

POST http://localhost:8080/tarefa
Content-type: application/json

{
    "Tarefa": "Estudar2"
}

###

PUT http://localhost:8080/tarefa?id=1
Content-type: application/json

{
    "Tarefa": "Es"
}