###

GET http://localhost:3000/users


###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Tesla da Silva", 
    "email": "tesla@gmail.com",
    "password": "Model S"
}



###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luiz Antonio", 
    "email": "luiz@gmail.com",
    "password": "luiz12345"
}