
GET http://localhost:8080/produtos

###



### POST 


###
POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "Celular",
    "preco": 1200,
    "descricao": "Celular preto"
}

###
POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "Notebook",
    "preco": 3200,
    "descricao": "Notebook core i5 16gb de ram"
}
###
POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "Teclado "
}


### PUT


###
PUT http://localhost:8080/produtos/1
Content-Type: application/json

{
    "nome": "Teclado ",
    "preco": 380,
    "descricao": "Teclado Gamer totalmente iluminado"
}

###
PUT http://localhost:8080/produtos/2
Content-Type: application/json

{
    "nome": "Alterando o produto 2"
}


###
DELETE http://localhost:8080/produtos/1

