
GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/1

###


POST http://localhost:8080/posts
Content-type: application/json

{
    "titulo": "Segundo titulo de teste",
    "texto": "esse é o segundo texto que utilizo como teste"
}

###
PUT http://localhost:8080/posts?id=2
Content-type: application/json

{
    "titulo": "Atualizando poste",
    "texto": "Estou atualizando o corpo do texto"
}


###
DELETE http://localhost:8080/posts?id=2
Content-type: application/json
