
GET http://localhost:8080/posts

###

GET http://localhost:8080/posts/1

###


POST http://localhost:8080/posts
Content-type: application/json

{
    "titulo": "Teste para verificar se insere 2",
    "texto": "esse é um teste para verificar se insere algo2",
    "userId": 1
}

###
PUT http://localhost:8080/posts?id=2
Content-type: application/json

{
    "titulo": "Atualizando poste",
    "texto": "Estou atualizando o corpo do texto",
    "userId": 1
}


###
DELETE http://localhost:8080/posts?id=2
Content-type: application/json
